"""Create refresh tokens table

Revision ID: 07b4ee6b4560
Revises: 8d6a3a8917f4
Create Date: 2026-08-10 17:56:45.562701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b4ee6b4560'
down_revision: Union[str, Sequence[str], None] = '8d6a3a8917f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('TokenHash', sa.String(length=64), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('RevokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_refresh_token_Id'), 'refresh_token', ['Id'], unique=False)
    op.create_index(op.f('ix_refresh_token_TokenHash'), 'refresh_token', ['TokenHash'], unique=True)
    op.create_index(op.f('ix_refresh_token_UserId'), 'refresh_token', ['UserId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_UserId'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_TokenHash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_Id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
