"""add document chunks

Revision ID: 594dca574bb8
Revises: e0761e4ada23
Create Date: 2026-09-19 23:07:26.770395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594dca574bb8'
down_revision: Union[str, Sequence[str], None] = 'e0761e4ada23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('KnowledgeItemId', sa.Integer(), nullable=False),
    sa.Column('ChunkIndex', sa.Integer(), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['KnowledgeItemId'], ['knowledge_items.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_document_chunks_Id'), 'document_chunks', ['Id'], unique=False)
    op.create_index(op.f('ix_document_chunks_KnowledgeItemId'), 'document_chunks', ['KnowledgeItemId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_KnowledgeItemId'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_Id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
