"""Add user role

Revision ID: 6ab18ed8c60a
Revises: 07b4ee6b4560
Create Date: 2026-08-11 02:41:36.018473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab18ed8c60a'
down_revision: Union[str, Sequence[str], None] = '07b4ee6b4560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.String(length=20), nullable=False, server_default='user,'))
    op.create_index(op.f('ix_users_Role'), 'users', ['Role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_Role'), table_name='users')
    op.drop_column('users', 'Role')
    # ### end Alembic commands ###
