"""Create knowledge items table

Revision ID: acfac48b01ee
Revises: 6ab18ed8c60a
Create Date: 2026-08-21 00:41:51.412218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfac48b01ee'
down_revision: Union[str, Sequence[str], None] = '6ab18ed8c60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('SourceUrl', sa.String(length=2048), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_knowledge_items_Id'), 'knowledge_items', ['Id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_UserId'), 'knowledge_items', ['UserId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_items_UserId'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_Id'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
