"""Add updated at to knowledge items

Revision ID: e0761e4ada23
Revises: 4d5ff8e510f3
Create Date: 2026-08-21 01:36:46.669603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0761e4ada23'
down_revision: Union[str, Sequence[str], None] = '4d5ff8e510f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('UpdatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE knowledge_items
        SET "UpdatedAt" = "CreatedAt"
        WHERE "UpdatedAt" IS NULL
        """
    )

    op.alter_column(
        "knowledge_items",
        "UpdatedAt",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_items', 'UpdatedAt')
    # ### end Alembic commands ###
